import type { Metadata } from "next";
import "./globals.css";
import { gilroy } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gilroy.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col text-primary bg-background font-medium text-[14px] leading-[1.29] tracking-[0.02em]">
        {children}
      </body>
    </html>
  );
}
